# ofono modems, bound to the binder slots in binder.d/qti.conf. Both slots
# enabled (vendor manifest serves slot1 and slot2). From fairphone-fp4.
[Settings]
SetRadioCapability=off
emptyPinQuery=false
radioPowerCycle=false
confirmRadioPowerOn=false

[ril_0]
transport=binder:name=slot1
name=slot1

[ril_1]
transport=binder:name=slot2
name=slot2
